apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web2-deployment
  labels:
    app : my-k8s2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: zsu2
  template:
    metadata:
      labels:
        project: zsu2
    spec:
      containers:
        - name : zsu2-web
          image: ivan231202/k8s-php-2:latest
          ports:
            - containerPort: 80
